#!/usr/bin/env node
import { execFileSync } from 'node:child_process';
import { existsSync, lstatSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { homedir } from 'node:os';
import { basename, dirname, join } from 'node:path';
import { env, execPath, platform, versions } from 'node:process';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const grammarRoot = fileURLToPath(new URL('..', import.meta.url));
const repoRoot = join(grammarRoot, '..', '..');
const headersRoot = join(grammarRoot, '.clangd-headers');
const isWindows = platform === 'win32';

function linkHeaderDir(name: string, source: string): void {
	const destination = join(headersRoot, name);
	mkdirSync(headersRoot, { recursive: true });
	if (existsSync(destination) || lstatExists(destination)) {
		rmSync(destination, { recursive: true, force: true });
	}
	symlinkSync(source, destination, isWindows ? 'junction' : 'dir');
}

function lstatExists(file: string): boolean {
	try {
		lstatSync(file);
		return true;
	} catch {
		return false;
	}
}

function resolveNodeGyp(): string | null {
	try {
		return require.resolve('node-gyp/bin/node-gyp.js');
	} catch {
		return null;
	}
}

function ensureNodeHeaders(): void {
	const includeDir = join(homedir(), '.cache', 'node-gyp', versions.node, 'include', 'node');
	if (!existsSync(join(includeDir, 'node_api.h'))) {
		const nodeGyp = resolveNodeGyp();
		if (nodeGyp) {
			execFileSync(execPath, [nodeGyp, 'install', '--ensure'], { stdio: 'inherit' });
		}
	}
	if (existsSync(join(includeDir, 'node_api.h'))) {
		linkHeaderDir('node', includeDir);
		return;
	}
	console.warn(`ensure-clangd-headers: missing Node headers at ${includeDir}`);
}

function resolvePython(): string {
	const configured = env.PYTHON;
	if (configured && existsSync(configured)) return configured;

	const venvPython = join(repoRoot, '.venv', isWindows ? 'Scripts' : 'bin', isWindows ? 'python.exe' : 'python3');
	if (existsSync(venvPython)) return venvPython;

	return isWindows ? 'python' : 'python3';
}

function pythonIncludeDir(python: string): string | null {
	try {
		return execFileSync(
			python,
			['-c', 'import sysconfig; print(sysconfig.get_path("include") or "")'],
			{ encoding: 'utf8' },
		).trim() || null;
	} catch {
		return null;
	}
}

function ensurePythonHeaders(): void {
	const python = resolvePython();
	const includeDir = pythonIncludeDir(python);
	if (includeDir && existsSync(join(includeDir, 'Python.h'))) {
		linkHeaderDir('python', includeDir);
		return;
	}
	console.warn(`ensure-clangd-headers: could not find Python.h using ${python}`);
}

ensureNodeHeaders();
ensurePythonHeaders();

function nodeAddonApiInclude(): string | null {
	try {
		return dirname(require.resolve('node-addon-api/package.json'));
	} catch {
		return null;
	}
}

function writeClangdConfig(): void {
	const bindingName = `${basename(grammarRoot).replace(/-/g, '_')}_binding`;
	const includes = [join(grammarRoot, 'src')];
	const addon = nodeAddonApiInclude();
	if (addon) {
		includes.push(addon);
	}
	includes.push(join(headersRoot, 'node'), join(headersRoot, 'python'));

	const lines = [
		'# Generated by scripts/ensure-clangd-headers.ts. Do not edit; gitignored.',
		'CompileFlags:',
		'  Add:',
		...includes.map((path) => `    - -I${path}`),
		`    - -DNODE_GYP_MODULE_NAME=${bindingName}`,
		'    - -DNAPI_CPP_EXCEPTIONS',
		'    - -DBUILDING_NODE_EXTENSION',
		'',
	];
	writeFileSync(join(grammarRoot, '.clangd'), `${lines.join('\n')}\n`);
}

writeClangdConfig();
