# Cargo configuration for the svg-language-server workspace.
# See: https://doc.rust-lang.org/cargo/reference/config.html
# Schema configured in ../tombi.toml

[alias]
br        = "build --release"
bw        = "build --workspace"
bwa       = "build --workspace --all-targets"
cw        = "check --workspace --all-targets"
dw        = "doc --workspace --no-deps"
dwn       = "--config .cargo/nightly.toml doc --workspace --exclude zed-svg --all-features"
fmt-check = "fmt --check"
fmt-svg   = "rb svg-format -q --manifest-path=crates/svg-format/Cargo.toml"
fmt-svg-r = "rbr svg-format -q --manifest-path=crates/svg-format/Cargo.toml"
i-fmt     = "install --path=crates/svg-format --bin=svg-format --force"
i-lint    = "install --path=crates/svg-lint --bin=svg-lint --force"
i-lsp     = "install --path=crates/svg-language-server --bin=svg-language-server --force"
lint      = "clippy --workspace --all-targets --all-features -- -D warnings -D clippy::all"
lsp       = "rb svg-language-server -q --manifest-path=crates/svg-language-server/Cargo.toml"
rb        = "run --bin"
rbr       = "run --release --bin"
rr        = "run --release"
svglint   = "rb svg-lint -q --manifest-path=crates/svg-lint/Cargo.toml"
tw        = "test --workspace"
twa       = "test --workspace --all-targets --all-features"
