#:schema https://raw.githubusercontent.com/kjanat/zed-editor/refs/heads/feature/extension-toml-schema/crates/extension_api/schemas/extension.schema.json

id             = "svg"
name           = "SVG"
version        = "0.1.0"
schema_version = 1
authors        = ["Kaj Kowalski <info@kajkowalski.nl>"]
description    = "Syntax highlighting and language injections for SVG files."
repository     = "https://github.com/kjanat/svg"
languages      = ["languages/svg", "languages/svg-paint", "languages/svg-path", "languages/svg-transform"]

# https://github.com/kjanat/svg-language-server
[grammars]
svg           = { repository = "file:///home/kjanat/svg-language-server", rev = "HEAD", path = "grammars/tree-sitter-svg" }
svg_path      = { repository = "file:///home/kjanat/svg-language-server", rev = "HEAD", path = "grammars/tree-sitter-svg-path" }
svg_transform = { repository = "file:///home/kjanat/svg-language-server", rev = "HEAD", path = "grammars/tree-sitter-svg-transform" }
svg_paint     = { repository = "file:///home/kjanat/svg-language-server", rev = "HEAD", path = "grammars/tree-sitter-svg-paint" }

[language_servers.svg-language-server]
languages        = ["SVG"]
language_ids.SVG = "svg"

[[capabilities]]
kind    = "npm:install"
package = "svg-language-server"
