#:schema https://raw.githubusercontent.com/kjanat/zed-editor/refs/heads/feature/extension-toml-schema/crates/extension_api/schemas/language-config.schema.json

name    = "SVG Paint and Color"
grammar = "svg_paint"
hidden  = true
