//! Full SVG 2 Editor's Draft spec inventory, baked from `definitions*.xml`.
//!
//! This is the **spec-faithful** companion to the curated catalog exposed by
//! [`crate::elements`] / [`crate::attributes`]. Where the curated catalog
//! encodes editorial decisions (dropping the full `aria-*`/`on*` families,
//! adding modern HTML/CSS attributes), this inventory is a *complete,
//! unfiltered* read of the vendored SVG 2 ED `definitions*.xml` family: every
//! element, every attribute the spec attaches to an element, and every
//! `(element, attribute)` edge, with each attribute classified by the
//! upstream `attributecategory` group(s) it was declared under.
//!
//! The backing data is generated by `build/spec_xml.rs` (the same extractor
//! audited by `tests/ed_presence_matrix.rs`) and emitted into `OUT_DIR` by the
//! build script, then `include!`d here — mirroring the
//! [`crate::edition`] baked-index pattern. No data is dropped: the raw
//! upstream category strings are preserved alongside the normalized
//! [`Classification`] so consumers (LSP completion, lint, audits) can pick or
//! compare on either the normalized bucket or the verbatim spec category.
//!
//! This layer is **additive**: it does not replace the curated catalog, and
//! the curated catalog's consumers are unaffected. Callers that want the
//! complete spec universe read [`SPEC_INVENTORY`]; callers that want the
//! curated, browser-reconciled view keep using the existing catalog APIs.

use std::borrow::Cow;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::SpecSnapshotId;

/// Normalized classification of an attribute, derived from the upstream
/// `attributecategory` group it was declared under.
///
/// An attribute may carry several classifications (the SVG 2 ED lists
/// `onunload` under both the `document event` and `window event` groups), so
/// callers see a *set* of these on each [`Attribute`]. The mapping is purely
/// derived from the upstream category name; the verbatim category strings are
/// retained on [`Attribute::raw_categories`] for provenance.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, JsonSchema,
)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Classification {
    /// The `core` attributecategory (`id`, `class`, `style`, `lang`,
    /// `tabindex`, `xml:space`, …).
    Core,
    /// The `presentation` attributecategory (CSS-property-backed presentation
    /// attributes such as `fill`, `stroke`, `opacity`).
    Presentation,
    /// The `aria` attributecategory (the `aria-*` family plus `role`).
    Aria,
    /// An event-handler category (`global event`, `document event`, `window
    /// event`, `animation event`) — the `on*` handler attributes.
    EventHandler,
    /// The `deprecated xlink` attributecategory (`xlink:href`,
    /// `xlink:title`).
    Xlink,
    /// The `conditional processing` attributecategory
    /// (`requiredExtensions`, `systemLanguage`).
    ConditionalProcessing,
    /// A classification whose upstream category is outside the named buckets
    /// (e.g. `filter primitive`, `transfer function element`, the non-event
    /// `animation *` categories). The wrapped string is the raw upstream
    /// category name, preserved verbatim so no spec datum is dropped.
    Other {
        /// Verbatim upstream `attributecategory` name.
        category: Cow<'static, str>,
    },
}

/// One element in the spec inventory: just its serialized tag name.
///
/// Elements carry no further spec-classification of their own here — the
/// classification model attaches to attributes. The element's content model,
/// categories, and compat data live on the curated [`crate::ElementDef`];
/// this record exists so the inventory is self-contained (its `(element,
/// attribute)` edges reference a declared element set).
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, JsonSchema,
)]
pub struct Element {
    /// Element tag name, for example `rect`.
    pub name: Cow<'static, str>,
}

/// One attribute in the spec inventory, with its normalized classifications,
/// raw upstream category provenance, and optional element scope.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct Attribute {
    /// Attribute name, for example `fill` or `aria-label`.
    pub name: Cow<'static, str>,
    /// Normalized classifications derived from [`Self::raw_categories`].
    /// Sorted and de-duplicated; empty for attributes the spec attaches only
    /// as element-local children or element-scoped top-level declarations
    /// (no `attributecategory` wrapper).
    pub classifications: Cow<'static, [Classification]>,
    /// Verbatim upstream `attributecategory` names this attribute appeared
    /// under, sorted and de-duplicated. Kept for provenance so consumers can
    /// distinguish, e.g., `document event` from `window event` even though
    /// both normalize to [`Classification::EventHandler`].
    pub raw_categories: Cow<'static, [Cow<'static, str>]>,
    /// Elements named in a top-level `<attribute name='x' elements='…'>`
    /// declaration. Empty when the attribute is not element-scoped this way.
    pub element_scope: Cow<'static, [Cow<'static, str>]>,
}

/// One resolved `(element, attribute)` edge of the spec matrix.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, JsonSchema,
)]
pub struct Edge {
    /// Element tag name the attribute applies to.
    pub element: Cow<'static, str>,
    /// Attribute name applied to [`Self::element`].
    pub attribute: Cow<'static, str>,
}

/// The complete, spec-faithful SVG 2 ED inventory: every element, every
/// classified attribute, and every `(element, attribute)` edge derived from
/// the vendored `definitions*.xml`.
///
/// All three slices are sorted: elements and edges by name, attributes by
/// name. Borrowed (`Cow::Borrowed`) when read from [`SPEC_INVENTORY`], so
/// reads are zero-allocation; the `Cow` shape also lets callers build or
/// deserialize an owned inventory when needed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct Inventory {
    /// Every `<element>` declared in the spec, sorted by name.
    pub elements: Cow<'static, [Element]>,
    /// Every attribute the spec attaches to an element, sorted by name, each
    /// carrying its classification and provenance.
    pub attributes: Cow<'static, [Attribute]>,
    /// Every resolved `(element, attribute)` edge, sorted.
    pub edges: Cow<'static, [Edge]>,
}

impl Inventory {
    /// Look up a single attribute's classification facts by name.
    #[must_use]
    pub fn attribute(&self, name: &str) -> Option<&Attribute> {
        self.attributes
            .iter()
            .find(|attribute| attribute.name == name)
    }

    /// Count attributes carrying the given classification. Useful for audits
    /// and for the LSP to size classification-bucketed completion lists.
    #[must_use]
    pub fn count_with_classification(&self, classification: &Classification) -> usize {
        self.attributes
            .iter()
            .filter(|attribute| attribute.classifications.contains(classification))
            .count()
    }

    /// Iterate the attributes the spec attaches to `element`, resolved through
    /// the `(element, attribute)` [`edges`](Self::edges) back to the full
    /// [`Attribute`] record (so callers get classification + provenance, not
    /// just a bare name).
    ///
    /// An attribute that appears in an edge but has no matching record in
    /// [`attributes`](Self::attributes) is skipped; the
    /// `every_edge_names_a_declared_element_and_attribute` test guarantees the
    /// baked data never has such dangling edges, so for [`SPEC_INVENTORY`]
    /// this yields exactly one record per applicable attribute. Yielded in the
    /// edges' sorted `(element, attribute)` order.
    pub fn attributes_for_element<'a, 'e>(
        &'a self,
        element: &'e str,
    ) -> impl Iterator<Item = &'a Attribute> + use<'a, 'e> {
        self.edges
            .iter()
            .filter(move |edge| edge.element == element)
            .filter_map(move |edge| self.attribute(edge.attribute.as_ref()))
    }

    /// Iterate every attribute matching the caller's `predicate` over its
    /// classification set. This is the general filter primitive behind the
    /// "consumers pick/compare whatever they need" goal: an LSP can request
    /// only [`Presentation`](Classification::Presentation) attributes, a lint
    /// can request everything *except* [`Aria`](Classification::Aria) and
    /// [`EventHandler`](Classification::EventHandler), an audit can match on a
    /// verbatim [`Other`](Classification::Other) category — all through the
    /// same call.
    ///
    /// The predicate receives the attribute's full, sorted, de-duplicated
    /// classification slice, so it can reason about combinations (e.g. "Core
    /// but not Presentation"). Yielded in the inventory's sorted-by-name order.
    pub fn attributes_where<'a, P>(
        &'a self,
        mut predicate: P,
    ) -> impl Iterator<Item = &'a Attribute>
    where
        P: FnMut(&[Classification]) -> bool + 'a,
    {
        self.attributes
            .iter()
            .filter(move |attribute| predicate(attribute.classifications.as_ref()))
    }

    /// Convenience filter: attributes carrying *at least one* of `wanted`.
    ///
    /// Empty `wanted` yields nothing. For the inverse ("everything except
    /// these buckets") use [`attributes_excluding`](Self::attributes_excluding).
    pub fn attributes_with_any<'a>(
        &'a self,
        wanted: &'a [Classification],
    ) -> impl Iterator<Item = &'a Attribute> + 'a {
        self.attributes_where(move |classifications| {
            classifications.iter().any(|c| wanted.contains(c))
        })
    }

    /// Convenience filter: attributes carrying *none* of `excluded`.
    ///
    /// With `excluded = [Aria, EventHandler]` this is the canonical "give me
    /// the spec attributes a normal completion list should show" query — it
    /// drops the bulky `aria-*`/`on*` families while keeping presentation,
    /// core, conditional-processing and the long tail. Empty `excluded` yields
    /// every attribute.
    pub fn attributes_excluding<'a>(
        &'a self,
        excluded: &'a [Classification],
    ) -> impl Iterator<Item = &'a Attribute> + 'a {
        self.attributes_where(move |classifications| {
            !classifications.iter().any(|c| excluded.contains(c))
        })
    }
}

include!(concat!(env!("OUT_DIR"), "/spec_inventory.rs"));
include!(concat!(env!("OUT_DIR"), "/svg11_inventory.rs"));

/// Return the baked spec inventory for `snapshot`, if one exists.
///
/// Three snapshots carry a baked, spec-faithful inventory, each derived from
/// the vendored grammar pinned for it:
///
/// - [`SpecSnapshotId::Svg2EditorsDraft`] — from the SVG 2 ED
///   `definitions*.xml` family (see [`SPEC_INVENTORY`]);
/// - [`SpecSnapshotId::Svg11Rec20030114`] and
///   [`SpecSnapshotId::Svg11Rec20110816`] — from each edition's flat SVG 1.1
///   DTD (see [`SVG11_REC_20030114_INVENTORY`] /
///   [`SVG11_REC_20110816_INVENTORY`]).
///
/// [`SpecSnapshotId::Svg2Cr20181004`] has no vendored machine-readable grammar
/// of its own and is modeled only by the curated, profile-aware catalog (see
/// [`crate::attributes_for_with_profile`]), so this returns [`None`] for it
/// rather than silently substituting another snapshot's data.
///
/// Returning [`Option`] keeps the "which snapshots have an inventory?" fact in
/// the type, so a consumer cannot accidentally treat an un-inventoried snapshot
/// as if it carried a full attribute universe.
///
/// This is re-exported at the crate root as [`crate::spec_inventory`] for
/// ergonomic access alongside the curated catalog APIs.
#[must_use]
pub fn for_snapshot(snapshot: SpecSnapshotId) -> Option<&'static Inventory> {
    match snapshot {
        SpecSnapshotId::Svg2EditorsDraft => Some(&SPEC_INVENTORY),
        SpecSnapshotId::Svg11Rec20030114 => Some(&SVG11_REC_20030114_INVENTORY),
        SpecSnapshotId::Svg11Rec20110816 => Some(&SVG11_REC_20110816_INVENTORY),
        SpecSnapshotId::Svg2Cr20181004 => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Look up an attribute or panic with a clear message. Avoids
    /// `.expect()`, which the workspace `expect_used` lint denies.
    fn require_attribute(name: &str) -> &'static Attribute {
        let Some(attribute) = SPEC_INVENTORY.attribute(name) else {
            panic!("`{name}` should be in the spec inventory")
        };
        attribute
    }

    #[test]
    fn inventory_counts_match_audited_extractor_figures() {
        // These figures are the audited reality at pin `19482daf`, the same
        // numbers locked by `tests/ed_presence_matrix.rs`. A drift here means
        // the baked inventory and the live extractor disagree — fail loudly.
        assert_eq!(SPEC_INVENTORY.elements.len(), 63, "element count drifted");
        assert_eq!(
            SPEC_INVENTORY.attributes.len(),
            313,
            "attribute count drifted"
        );
        assert_eq!(SPEC_INVENTORY.edges.len(), 6752, "edge count drifted");
    }

    #[test]
    fn presentation_classification_reaches_fill() {
        let fill = require_attribute("fill");
        assert!(
            fill.classifications.contains(&Classification::Presentation),
            "fill should be classified Presentation: {:?}",
            fill.classifications
        );
    }

    #[test]
    fn aria_family_is_classified_aria() {
        let label = require_attribute("aria-label");
        assert!(label.classifications.contains(&Classification::Aria));
        // `role` rides in the same upstream `aria` category.
        let role = require_attribute("role");
        assert!(role.classifications.contains(&Classification::Aria));
    }

    #[test]
    fn onunload_carries_both_event_categories_as_provenance() {
        // `onunload` is declared under both `document event` and `window
        // event`. It normalizes to a single EventHandler classification but
        // both raw categories survive for provenance.
        let onunload = require_attribute("onunload");
        assert!(
            onunload
                .classifications
                .contains(&Classification::EventHandler)
        );
        let raw: Vec<&str> = onunload
            .raw_categories
            .iter()
            .map(std::convert::AsRef::as_ref)
            .collect();
        assert!(raw.contains(&"document event"), "raw categories: {raw:?}");
        assert!(raw.contains(&"window event"), "raw categories: {raw:?}");
    }

    #[test]
    fn xlink_attributes_are_classified_xlink() {
        let href = require_attribute("xlink:href");
        assert!(href.classifications.contains(&Classification::Xlink));
    }

    #[test]
    fn element_scoped_attribute_records_its_scope() {
        // `rotate` is a top-level `<attribute elements='tspan'>` declaration.
        let rotate = require_attribute("rotate");
        let scope: Vec<&str> = rotate
            .element_scope
            .iter()
            .map(std::convert::AsRef::as_ref)
            .collect();
        assert!(scope.contains(&"tspan"), "element scope: {scope:?}");
    }

    #[test]
    fn every_edge_names_a_declared_element_and_attribute() {
        let element_names: std::collections::BTreeSet<&str> = SPEC_INVENTORY
            .elements
            .iter()
            .map(|element| element.name.as_ref())
            .collect();
        let attribute_names: std::collections::BTreeSet<&str> = SPEC_INVENTORY
            .attributes
            .iter()
            .map(|attribute| attribute.name.as_ref())
            .collect();
        for edge in SPEC_INVENTORY.edges.iter() {
            assert!(
                element_names.contains(edge.element.as_ref()),
                "edge names unknown element <{}>",
                edge.element
            );
            assert!(
                attribute_names.contains(edge.attribute.as_ref()),
                "edge names unknown attribute `{}`",
                edge.attribute
            );
        }
    }
}
