//! Full SVG 2 Editor's Draft spec inventory, baked from `definitions*.xml`.
//!
//! This is the **spec-faithful** companion to the curated catalog exposed by
//! [`crate::elements`] / [`crate::attributes`]. Where the curated catalog
//! encodes editorial decisions (dropping the full `aria-*`/`on*` families,
//! adding modern HTML/CSS attributes), this inventory is a *complete,
//! unfiltered* read of the vendored SVG 2 ED `definitions*.xml` family: every
//! element, every attribute the spec attaches to an element, and every
//! `(element, attribute)` edge, with each attribute classified by the
//! upstream `attributecategory` group(s) it was declared under.
//!
//! The backing data is generated by `build/spec_xml.rs` (the same extractor
//! audited by `tests/ed_presence_matrix.rs`) and emitted into `OUT_DIR` by the
//! build script, then `include!`d here — mirroring the
//! [`crate::edition`] baked-index pattern. No data is dropped: the raw
//! upstream category strings are preserved alongside the normalized
//! [`Classification`] so consumers (LSP completion, lint, audits) can pick or
//! compare on either the normalized bucket or the verbatim spec category.
//!
//! This layer is **additive**: it does not replace the curated catalog, and
//! the curated catalog's consumers are unaffected. Callers that want the
//! complete spec universe read [`SPEC_INVENTORY`]; callers that want the
//! curated, browser-reconciled view keep using the existing catalog APIs.

use std::borrow::Cow;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::SpecSnapshotId;
use crate::edition::Series;

/// Normalized classification of an attribute, derived from the upstream
/// `attributecategory` group it was declared under.
///
/// An attribute may carry several classifications (the SVG 2 ED lists
/// `onunload` under both the `document event` and `window event` groups), so
/// callers see a *set* of these on each [`Attribute`]. The mapping is purely
/// derived from the upstream category name; the verbatim category strings are
/// retained on [`Attribute::raw_categories`] for provenance.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, JsonSchema,
)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Classification {
    /// The `core` attributecategory (`id`, `class`, `style`, `lang`,
    /// `tabindex`, `xml:space`, …).
    Core,
    /// The `presentation` attributecategory (CSS-property-backed presentation
    /// attributes such as `fill`, `stroke`, `opacity`).
    Presentation,
    /// The `aria` attributecategory (the `aria-*` family plus `role`).
    Aria,
    /// An event-handler category (`global event`, `document event`, `window
    /// event`, `animation event`) — the `on*` handler attributes.
    EventHandler,
    /// The `deprecated xlink` attributecategory (`xlink:href`,
    /// `xlink:title`).
    Xlink,
    /// The `conditional processing` attributecategory
    /// (`requiredExtensions`, `systemLanguage`).
    ConditionalProcessing,
    /// A classification whose upstream category is outside the named buckets
    /// (e.g. `filter primitive`, `transfer function element`, the non-event
    /// `animation *` categories). The wrapped string is the raw upstream
    /// category name, preserved verbatim so no spec datum is dropped.
    Other {
        /// Verbatim upstream `attributecategory` name.
        category: Cow<'static, str>,
    },
}

/// One element in the spec inventory: just its serialized tag name.
///
/// Elements carry no further spec-classification of their own here — the
/// classification model attaches to attributes. The element's content model,
/// categories, and compat data live on the curated [`crate::ElementDef`];
/// this record exists so the inventory is self-contained (its `(element,
/// attribute)` edges reference a declared element set).
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, JsonSchema,
)]
pub struct Element {
    /// Element tag name, for example `rect`.
    pub name: Cow<'static, str>,
}

/// One attribute in the spec inventory, with its normalized classifications,
/// raw upstream category provenance, and optional element scope.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct Attribute {
    /// Attribute name, for example `fill` or `aria-label`.
    pub name: Cow<'static, str>,
    /// Normalized classifications derived from [`Self::raw_categories`].
    /// Sorted and de-duplicated; empty for attributes the spec attaches only
    /// as element-local children or element-scoped top-level declarations
    /// (no `attributecategory` wrapper).
    pub classifications: Cow<'static, [Classification]>,
    /// Verbatim upstream `attributecategory` names this attribute appeared
    /// under, sorted and de-duplicated. Kept for provenance so consumers can
    /// distinguish, e.g., `document event` from `window event` even though
    /// both normalize to [`Classification::EventHandler`].
    pub raw_categories: Cow<'static, [Cow<'static, str>]>,
    /// Elements named in a top-level `<attribute name='x' elements='…'>`
    /// declaration. Empty when the attribute is not element-scoped this way.
    pub element_scope: Cow<'static, [Cow<'static, str>]>,
}

/// One resolved `(element, attribute)` edge of the spec matrix.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, JsonSchema,
)]
pub struct Edge {
    /// Element tag name the attribute applies to.
    pub element: Cow<'static, str>,
    /// Attribute name applied to [`Self::element`].
    pub attribute: Cow<'static, str>,
}

/// The complete, spec-faithful SVG 2 ED inventory: every element, every
/// classified attribute, and every `(element, attribute)` edge derived from
/// the vendored `definitions*.xml`.
///
/// All three slices are sorted: elements and edges by name, attributes by
/// name. Borrowed (`Cow::Borrowed`) when read from [`SPEC_INVENTORY`], so
/// reads are zero-allocation; the `Cow` shape also lets callers build or
/// deserialize an owned inventory when needed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct Inventory {
    /// Every `<element>` declared in the spec, sorted by name.
    pub elements: Cow<'static, [Element]>,
    /// Every attribute the spec attaches to an element, sorted by name, each
    /// carrying its classification and provenance.
    pub attributes: Cow<'static, [Attribute]>,
    /// Every resolved `(element, attribute)` edge, sorted.
    pub edges: Cow<'static, [Edge]>,
}

impl Inventory {
    /// Look up a single attribute's classification facts by name.
    #[must_use]
    pub fn attribute(&self, name: &str) -> Option<&Attribute> {
        self.attributes
            .iter()
            .find(|attribute| attribute.name == name)
    }

    /// Count attributes carrying the given classification. Useful for audits
    /// and for the LSP to size classification-bucketed completion lists.
    #[must_use]
    pub fn count_with_classification(&self, classification: &Classification) -> usize {
        self.attributes
            .iter()
            .filter(|attribute| attribute.classifications.contains(classification))
            .count()
    }

    /// Iterate the attributes the spec attaches to `element`, resolved through
    /// the `(element, attribute)` [`edges`](Self::edges) back to the full
    /// [`Attribute`] record (so callers get classification + provenance, not
    /// just a bare name).
    ///
    /// An attribute that appears in an edge but has no matching record in
    /// [`attributes`](Self::attributes) is skipped; the
    /// `every_edge_names_a_declared_element_and_attribute` test guarantees the
    /// baked data never has such dangling edges, so for [`SPEC_INVENTORY`]
    /// this yields exactly one record per applicable attribute. Yielded in the
    /// edges' sorted `(element, attribute)` order.
    pub fn attributes_for_element<'a, 'e>(
        &'a self,
        element: &'e str,
    ) -> impl Iterator<Item = &'a Attribute> + use<'a, 'e> {
        self.edges
            .iter()
            .filter(move |edge| edge.element == element)
            .filter_map(move |edge| self.attribute(edge.attribute.as_ref()))
    }

    /// Iterate every attribute matching the caller's `predicate` over its
    /// classification set. This is the general filter primitive behind the
    /// "consumers pick/compare whatever they need" goal: an LSP can request
    /// only [`Presentation`](Classification::Presentation) attributes, a lint
    /// can request everything *except* [`Aria`](Classification::Aria) and
    /// [`EventHandler`](Classification::EventHandler), an audit can match on a
    /// verbatim [`Other`](Classification::Other) category — all through the
    /// same call.
    ///
    /// The predicate receives the attribute's full, sorted, de-duplicated
    /// classification slice, so it can reason about combinations (e.g. "Core
    /// but not Presentation"). Yielded in the inventory's sorted-by-name order.
    pub fn attributes_where<'a, P>(
        &'a self,
        mut predicate: P,
    ) -> impl Iterator<Item = &'a Attribute>
    where
        P: FnMut(&[Classification]) -> bool + 'a,
    {
        self.attributes
            .iter()
            .filter(move |attribute| predicate(attribute.classifications.as_ref()))
    }

    /// Convenience filter: attributes carrying *at least one* of `wanted`.
    ///
    /// Empty `wanted` yields nothing. For the inverse ("everything except
    /// these buckets") use [`attributes_excluding`](Self::attributes_excluding).
    pub fn attributes_with_any<'a>(
        &'a self,
        wanted: &'a [Classification],
    ) -> impl Iterator<Item = &'a Attribute> + 'a {
        self.attributes_where(move |classifications| {
            classifications.iter().any(|c| wanted.contains(c))
        })
    }

    /// Convenience filter: attributes carrying *none* of `excluded`.
    ///
    /// With `excluded = [Aria, EventHandler]` this is the canonical "give me
    /// the spec attributes a normal completion list should show" query — it
    /// drops the bulky `aria-*`/`on*` families while keeping presentation,
    /// core, conditional-processing and the long tail. Empty `excluded` yields
    /// every attribute.
    pub fn attributes_excluding<'a>(
        &'a self,
        excluded: &'a [Classification],
    ) -> impl Iterator<Item = &'a Attribute> + 'a {
        self.attributes_where(move |classifications| {
            !classifications.iter().any(|c| excluded.contains(c))
        })
    }
}

include!(concat!(env!("OUT_DIR"), "/spec_inventory.rs"));
include!(concat!(env!("OUT_DIR"), "/svg11_inventory.rs"));
include!(concat!(env!("OUT_DIR"), "/cr_inventory.rs"));

/// Return the baked spec inventory for `snapshot`.
///
/// All four snapshots carry a baked, spec-faithful inventory, each derived from
/// the machine-readable artifact pinned for it:
///
/// - [`SpecSnapshotId::Svg2EditorsDraft`] — from the SVG 2 ED
///   `definitions*.xml` family (see [`SPEC_INVENTORY`]);
/// - [`SpecSnapshotId::Svg11Rec20030114`] and
///   [`SpecSnapshotId::Svg11Rec20110816`] — from each edition's flat SVG 1.1
///   DTD (see [`SVG11_REC_20030114_INVENTORY`] /
///   [`SVG11_REC_20110816_INVENTORY`]);
/// - [`SpecSnapshotId::Svg2Cr20181004`] — from the CR's *published* index
///   tables (`eltindex.html` + `attindex.html`; see
///   [`SVG2_CR_20181004_INVENTORY`]). Unlike the ED's `definitions*.xml`, the
///   rendered CR index carries no `attributecategory` groups, so its
///   attributes are faithfully **unclassified** — the animatable flag the
///   index *does* expose is retained as provenance instead. This makes the CR
///   inventory's classification deliberately sparser than the
///   `definitions.xml`/DTD editions, reflecting exactly what the CR's own
///   machine-readable artifact exposes.
///
/// Now that every snapshot has an inventory this never returns [`None`], but
/// the signature stays [`Option`] so adding a future un-inventoried snapshot
/// cannot silently fabricate an attribute universe.
///
/// This is re-exported at the crate root as [`crate::spec_inventory`] for
/// ergonomic access alongside the curated catalog APIs.
#[must_use]
pub fn for_snapshot(snapshot: SpecSnapshotId) -> Option<&'static Inventory> {
    match snapshot {
        SpecSnapshotId::Svg2EditorsDraft => Some(&SPEC_INVENTORY),
        SpecSnapshotId::Svg11Rec20030114 => Some(&SVG11_REC_20030114_INVENTORY),
        SpecSnapshotId::Svg11Rec20110816 => Some(&SVG11_REC_20110816_INVENTORY),
        SpecSnapshotId::Svg2Cr20181004 => Some(&SVG2_CR_20181004_INVENTORY),
    }
}

/// The point in an edition's lifecycle the [`EditionId`] addresses.
///
/// Frozen `/TR/` publications are pinned by their dated ISO-8601 publication
/// date — the same `date` the [`crate::edition::PublishedVersion`] index keys
/// on. The rolling editor's draft is undated by design (its commit pin lives in
/// the snapshot data, not in a Rust constant), so it is addressed by the
/// [`EditionDate::EditorsDraft`] sentinel instead of a fabricated date. Modeling
/// the two as distinct variants keeps an undated edition from masquerading as a
/// dated one.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, JsonSchema,
)]
#[serde(rename_all = "snake_case")]
pub enum EditionDate {
    /// A dated `/TR/` publication, keyed by its ISO-8601 `YYYY-MM-DD` date.
    Dated {
        /// ISO-8601 publication date, e.g. `2016-09-15`.
        date: Cow<'static, str>,
    },
    /// The rolling SVG 2 editor's draft, which carries no `/TR/` date.
    EditorsDraft,
}

/// The natural, edition-level key for an inventory: the spec [`Series`] plus the
/// point in its lifecycle ([`EditionDate`]).
///
/// This is the **additive** counterpart to [`SpecSnapshotId`]. Where
/// `SpecSnapshotId` is the curated catalog's fixed four-snapshot enum, an
/// `EditionId` can address *any* edition that has a baked inventory —
/// including the two older SVG 2 CRs (2016-09-15, 2018-08-07) that are not
/// curated snapshots — through one uniform key. Every curated snapshot also has
/// an `EditionId` (see [`EditionId::for_snapshot`]), so all registered editions
/// are queryable through the same [`for_edition`] entry point.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, JsonSchema,
)]
pub struct EditionId {
    /// The spec series this edition belongs to.
    pub series: Series,
    /// The dated publication, or the undated editor's-draft sentinel.
    pub date: EditionDate,
}

impl EditionId {
    /// Construct a dated edition key from a series and ISO-8601 date.
    #[must_use]
    pub const fn dated(series: Series, date: &'static str) -> Self {
        Self {
            series,
            date: EditionDate::Dated {
                date: Cow::Borrowed(date),
            },
        }
    }

    /// Construct the undated SVG 2 editor's-draft edition key.
    #[must_use]
    pub const fn editors_draft(series: Series) -> Self {
        Self {
            series,
            date: EditionDate::EditorsDraft,
        }
    }

    /// The `EditionId` a curated [`SpecSnapshotId`] maps onto.
    ///
    /// Frozen snapshots map to their dated `/TR/` publication date; the rolling
    /// [`SpecSnapshotId::Svg2EditorsDraft`] maps to the undated
    /// [`EditionDate::EditorsDraft`] sentinel. This is the bridge that lets the
    /// four curated snapshots be looked up through the same edition-keyed entry
    /// point as the additive (non-snapshot) editions.
    #[must_use]
    pub const fn for_snapshot(snapshot: SpecSnapshotId) -> Self {
        match snapshot {
            SpecSnapshotId::Svg11Rec20030114 => Self::dated(Series::Svg11, "2003-01-14"),
            SpecSnapshotId::Svg11Rec20110816 => Self::dated(Series::Svg11, "2011-08-16"),
            SpecSnapshotId::Svg2Cr20181004 => Self::dated(Series::Svg2, "2018-10-04"),
            SpecSnapshotId::Svg2EditorsDraft => Self::editors_draft(Series::Svg2),
        }
    }
}

/// The full registry of edition-keyed inventories, baked into the binary.
///
/// Every entry pairs an [`EditionId`] with the `&'static` [`Inventory`] derived
/// from that edition's vendored machine-readable artifact. This is the single
/// uniform table behind [`for_edition`] and [`registered_editions`];
/// it is a superset of the four [`for_snapshot`] inventories — it *additionally*
/// registers editions that have no [`SpecSnapshotId`]: the SVG 1.0 REC
/// (2001-09-04), the SVG 1.1 Proposed Recommendation (2011-06-09), and the two
/// older SVG 2 CRs (2016-09-15, 2018-08-07).
///
/// Held as a plain slice of borrowing entries (no allocation, no `OnceLock`):
/// every referenced `Inventory` is itself a `'static` baked literal.
static EDITION_INVENTORIES: &[(EditionEntry, &Inventory)] = &[
    (
        EditionEntry {
            series: Series::Svg10,
            date: EditionDateKey::Dated("2001-09-04"),
        },
        &SVG10_REC_20010904_INVENTORY,
    ),
    (
        EditionEntry {
            series: Series::Svg11,
            date: EditionDateKey::Dated("2003-01-14"),
        },
        &SVG11_REC_20030114_INVENTORY,
    ),
    (
        EditionEntry {
            series: Series::Svg11,
            date: EditionDateKey::Dated("2011-06-09"),
        },
        &SVG11_PR_20110609_INVENTORY,
    ),
    (
        EditionEntry {
            series: Series::Svg11,
            date: EditionDateKey::Dated("2011-08-16"),
        },
        &SVG11_REC_20110816_INVENTORY,
    ),
    (
        EditionEntry {
            series: Series::Svg2,
            date: EditionDateKey::Dated("2016-09-15"),
        },
        &SVG2_CR_20160915_INVENTORY,
    ),
    (
        EditionEntry {
            series: Series::Svg2,
            date: EditionDateKey::Dated("2018-08-07"),
        },
        &SVG2_CR_20180807_INVENTORY,
    ),
    (
        EditionEntry {
            series: Series::Svg2,
            date: EditionDateKey::Dated("2018-10-04"),
        },
        &SVG2_CR_20181004_INVENTORY,
    ),
    (
        EditionEntry {
            series: Series::Svg2,
            date: EditionDateKey::EditorsDraft,
        },
        &SPEC_INVENTORY,
    ),
];

/// `const`-friendly mirror of [`EditionDate`] using a borrowed `&'static str`,
/// so the [`EDITION_INVENTORIES`] table is a plain `static` (no allocation).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum EditionDateKey {
    Dated(&'static str),
    EditorsDraft,
}

/// `const`-friendly mirror of [`EditionId`] for the baked [`EDITION_INVENTORIES`]
/// table.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct EditionEntry {
    series: Series,
    date: EditionDateKey,
}

impl EditionEntry {
    /// Whether this baked key denotes the same edition as a runtime [`EditionId`].
    fn matches(&self, id: &EditionId) -> bool {
        if self.series != id.series {
            return false;
        }
        match (&self.date, &id.date) {
            (EditionDateKey::Dated(baked), EditionDate::Dated { date }) => *baked == date.as_ref(),
            (EditionDateKey::EditorsDraft, EditionDate::EditorsDraft) => true,
            _ => false,
        }
    }

    /// Reconstruct the owning [`EditionId`] from this baked key.
    const fn to_id(self) -> EditionId {
        match self.date {
            EditionDateKey::Dated(date) => EditionId::dated(self.series, date),
            EditionDateKey::EditorsDraft => EditionId::editors_draft(self.series),
        }
    }
}

/// Return the baked inventory registered under `id`, if any.
///
/// This is the additive, edition-keyed companion to [`for_snapshot`]: it
/// resolves *every* registered edition — the four curated snapshots **and** the
/// two older SVG 2 CRs that have no [`SpecSnapshotId`] — through one uniform key.
/// Returns [`None`] for an edition with no baked inventory.
#[must_use]
pub fn for_edition(id: &EditionId) -> Option<&'static Inventory> {
    EDITION_INVENTORIES
        .iter()
        .find(|(entry, _)| entry.matches(id))
        .map(|(_, inventory)| *inventory)
}

/// The series token used in an edition's canonical config key.
const fn series_token(series: Series) -> &'static str {
    match series {
        Series::Svg10 => "svg10",
        Series::Svg11 => "svg11",
        Series::Svg2 => "svg2",
    }
}

impl EditionId {
    /// The canonical, user-facing config key for this edition.
    ///
    /// Dated editions render as `<series>-<date>` (e.g. `svg2-2016-09-15`); the
    /// rolling editor's draft renders as `<series>-editors-draft` (e.g.
    /// `svg2-editors-draft`). This is the stable token an LSP config or
    /// diagnostic uses to name an edition — including the three editions that
    /// have no [`SpecSnapshotId`] — and the canonical form
    /// [`resolve_edition_id`] resolves against.
    #[must_use]
    pub fn config_key(&self) -> String {
        match &self.date {
            EditionDate::Dated { date } => format!("{}-{date}", series_token(self.series)),
            EditionDate::EditorsDraft => format!("{}-editors-draft", series_token(self.series)),
        }
    }
}

/// Resolve a user-facing edition config string to a registered [`EditionId`].
///
/// This is the edition-keyed analogue of
/// [`resolve_profile_id`](crate::resolve_profile_id): where `resolve_profile_id`
/// resolves the four curated [`SpecSnapshotId`] snapshots, this resolves *every*
/// registered edition — including the SVG 1.0 REC, the SVG 1.1 PR, and the two
/// older SVG 2 CRs that carry no `SpecSnapshotId` — so an LSP can target those
/// inventories from config.
///
/// Matching is normalized: ASCII case and every non-alphanumeric character are
/// folded away on both sides, so `svg2-2016-09-15`, `SVG2 20160915`, and
/// `svg2_2016_09_15` all resolve to the same edition, and `svg2-editors-draft`,
/// `Svg2EditorsDraft`, and `svg2 editor's draft` all resolve to the rolling
/// draft. Returns the matching [`EditionId`] (which [`for_edition`] then maps to
/// its baked [`Inventory`]), or [`None`] when nothing registered matches.
///
/// Only registered editions resolve; an input that does not match one returns
/// [`None`] rather than fabricating an edition key.
#[must_use]
pub fn resolve_edition_id(input: &str) -> Option<EditionId> {
    let normalized_input = normalize_edition_key(input);
    if normalized_input.is_empty() {
        return None;
    }
    registered_editions()
        .into_iter()
        .find(|edition| normalize_edition_key(&edition.config_key()) == normalized_input)
}

/// Fold ASCII case and strip every non-alphanumeric character, so punctuation
/// and separator differences between edition config strings do not matter.
fn normalize_edition_key(input: &str) -> String {
    input
        .chars()
        .filter(char::is_ascii_alphanumeric)
        .map(|ch| ch.to_ascii_lowercase())
        .collect()
}

/// Every edition that has a baked, edition-keyed inventory, in registration
/// order.
///
/// The order is: the SVG 1.0 REC, then the SVG 1.1 editions oldest-first, then
/// the SVG 2 CRs oldest-first, then the rolling editor's draft. Lets a consumer
/// enumerate the complete editioned universe — including the non-snapshot
/// SVG 1.0 REC, SVG 1.1 PR, and SVG 2 CRs — and pair each [`EditionId`] with its
/// [`Inventory`] via [`for_edition`] for cross-edition comparison.
#[must_use]
pub fn registered_editions() -> Vec<EditionId> {
    EDITION_INVENTORIES
        .iter()
        .map(|(entry, _)| entry.to_id())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Look up an attribute or panic with a clear message. Avoids
    /// `.expect()`, which the workspace `expect_used` lint denies.
    fn require_attribute(name: &str) -> &'static Attribute {
        let Some(attribute) = SPEC_INVENTORY.attribute(name) else {
            panic!("`{name}` should be in the spec inventory")
        };
        attribute
    }

    #[test]
    fn inventory_counts_match_audited_extractor_figures() {
        // These figures are the audited reality at pin `19482daf`, the same
        // numbers locked by `tests/ed_presence_matrix.rs`. A drift here means
        // the baked inventory and the live extractor disagree — fail loudly.
        assert_eq!(SPEC_INVENTORY.elements.len(), 63, "element count drifted");
        assert_eq!(
            SPEC_INVENTORY.attributes.len(),
            313,
            "attribute count drifted"
        );
        assert_eq!(SPEC_INVENTORY.edges.len(), 6752, "edge count drifted");
    }

    #[test]
    fn presentation_classification_reaches_fill() {
        let fill = require_attribute("fill");
        assert!(
            fill.classifications.contains(&Classification::Presentation),
            "fill should be classified Presentation: {:?}",
            fill.classifications
        );
    }

    #[test]
    fn aria_family_is_classified_aria() {
        let label = require_attribute("aria-label");
        assert!(label.classifications.contains(&Classification::Aria));
        // `role` rides in the same upstream `aria` category.
        let role = require_attribute("role");
        assert!(role.classifications.contains(&Classification::Aria));
    }

    #[test]
    fn onunload_carries_both_event_categories_as_provenance() {
        // `onunload` is declared under both `document event` and `window
        // event`. It normalizes to a single EventHandler classification but
        // both raw categories survive for provenance.
        let onunload = require_attribute("onunload");
        assert!(
            onunload
                .classifications
                .contains(&Classification::EventHandler)
        );
        let raw: Vec<&str> = onunload
            .raw_categories
            .iter()
            .map(std::convert::AsRef::as_ref)
            .collect();
        assert!(raw.contains(&"document event"), "raw categories: {raw:?}");
        assert!(raw.contains(&"window event"), "raw categories: {raw:?}");
    }

    #[test]
    fn xlink_attributes_are_classified_xlink() {
        let href = require_attribute("xlink:href");
        assert!(href.classifications.contains(&Classification::Xlink));
    }

    #[test]
    fn element_scoped_attribute_records_its_scope() {
        // `rotate` is a top-level `<attribute elements='tspan'>` declaration.
        let rotate = require_attribute("rotate");
        let scope: Vec<&str> = rotate
            .element_scope
            .iter()
            .map(std::convert::AsRef::as_ref)
            .collect();
        assert!(scope.contains(&"tspan"), "element scope: {scope:?}");
    }

    #[test]
    fn resolve_edition_id_resolves_canonical_keys_for_every_registered_edition() {
        // Round-trip: every registered edition resolves from its own canonical
        // config key, and the resolved id maps back to a baked inventory.
        for edition in registered_editions() {
            let key = edition.config_key();
            assert_eq!(
                resolve_edition_id(&key),
                Some(edition.clone()),
                "edition {key} should resolve from its canonical key"
            );
            assert!(
                for_edition(&edition).is_some(),
                "edition {key} should have a baked inventory"
            );
        }
    }

    #[test]
    fn resolve_edition_id_resolves_non_snapshot_editions() {
        // The two older SVG 2 CRs carry no SpecSnapshotId, but are reachable
        // through the edition-keyed resolver.
        assert_eq!(
            resolve_edition_id("svg2-2016-09-15"),
            Some(EditionId::dated(Series::Svg2, "2016-09-15"))
        );
        assert_eq!(
            resolve_edition_id("svg10-2001-09-04"),
            Some(EditionId::dated(Series::Svg10, "2001-09-04"))
        );
    }

    #[test]
    fn resolve_edition_id_ignores_case_and_punctuation() {
        let expected = EditionId::dated(Series::Svg2, "2018-08-07");
        for input in ["svg2-2018-08-07", "SVG2 20180807", "svg2_2018_08_07"] {
            assert_eq!(resolve_edition_id(input), Some(expected.clone()), "{input}");
        }
        assert_eq!(
            resolve_edition_id("Svg2 Editor's Draft"),
            Some(EditionId::editors_draft(Series::Svg2))
        );
    }

    #[test]
    fn resolve_edition_id_rejects_unregistered_and_empty_input() {
        assert_eq!(resolve_edition_id(""), None);
        assert_eq!(resolve_edition_id("   "), None);
        // A plausible-but-unregistered date.
        assert_eq!(resolve_edition_id("svg2-1999-01-01"), None);
    }

    #[test]
    fn every_edge_names_a_declared_element_and_attribute() {
        let element_names: std::collections::BTreeSet<&str> = SPEC_INVENTORY
            .elements
            .iter()
            .map(|element| element.name.as_ref())
            .collect();
        let attribute_names: std::collections::BTreeSet<&str> = SPEC_INVENTORY
            .attributes
            .iter()
            .map(|attribute| attribute.name.as_ref())
            .collect();
        for edge in SPEC_INVENTORY.edges.iter() {
            assert!(
                element_names.contains(edge.element.as_ref()),
                "edge names unknown element <{}>",
                edge.element
            );
            assert!(
                attribute_names.contains(edge.attribute.as_ref()),
                "edge names unknown attribute `{}`",
                edge.attribute
            );
        }
    }
}
