use serde::Deserialize;
use std::collections::HashMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

// ---- JSON schema types ----

#[derive(Deserialize)]
struct JsonElement {
    name: String,
    description: String,
    mdn_url: String,
    deprecated: bool,
    content_model: ContentModelJson,
    required_attrs: Vec<String>,
    attrs: Vec<String>,
    global_attrs: bool,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum ContentModelJson {
    Simple(String),
    Children { children: Vec<String> },
}

#[derive(Deserialize)]
struct JsonAttribute {
    name: String,
    description: String,
    mdn_url: String,
    deprecated: bool,
    values: ValuesJson,
    elements: Vec<String>,
}

#[derive(Deserialize)]
#[serde(tag = "type")]
#[serde(rename_all = "snake_case")]
enum ValuesJson {
    Enum {
        values: Vec<String>,
    },
    FreeText,
    Color,
    Length,
    Url,
    NumberOrPercentage,
    Transform {
        functions: Vec<String>,
    },
    Viewbox,
    PreserveAspectRatio {
        alignments: Vec<String>,
        meet_or_slice: Vec<String>,
    },
    Points,
    PathData,
}

// ---- Codegen helpers ----

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn write_static_str_slice(out: &mut String, name: &str, items: &[String]) {
    write!(out, "static {name}: &[&str] = &[").unwrap();
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        write!(out, "\"{}\"", escape(item)).unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn ident_from(name: &str) -> String {
    name.replace('-', "_").to_uppercase()
}

fn main() {
    println!("cargo::rerun-if-changed=data/elements.json");
    println!("cargo::rerun-if-changed=data/attributes.json");

    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("catalog.rs");

    let elements_json = fs::read_to_string(manifest_dir.join("data/elements.json"))
        .expect("failed to read elements.json");
    let attributes_json = fs::read_to_string(manifest_dir.join("data/attributes.json"))
        .expect("failed to read attributes.json");

    let elements: Vec<JsonElement> =
        serde_json::from_str(&elements_json).expect("failed to parse elements.json");
    let attributes: Vec<JsonAttribute> =
        serde_json::from_str(&attributes_json).expect("failed to parse attributes.json");

    let mut out = String::with_capacity(16384);

    writeln!(out, "// @generated by build.rs -- do not edit").unwrap();
    writeln!(out).unwrap();

    // ---- Element statics ----

    // Build a map of element name -> index for unique static names
    let el_idents: HashMap<&str, String> = elements
        .iter()
        .map(|e| (e.name.as_str(), ident_from(&e.name)))
        .collect();

    for el in &elements {
        let id = &el_idents[el.name.as_str()];

        write_static_str_slice(
            &mut out,
            &format!("EL_{id}_REQUIRED_ATTRS"),
            &el.required_attrs,
        );
        write_static_str_slice(&mut out, &format!("EL_{id}_ATTRS"), &el.attrs);

        // Children categories (if applicable)
        if let ContentModelJson::Children { children } = &el.content_model {
            write!(out, "static EL_{id}_CHILDREN: &[ElementCategory] = &[").unwrap();
            for (i, cat) in children.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                write!(out, "ElementCategory::{cat}").unwrap();
            }
            writeln!(out, "];").unwrap();
        }

        writeln!(out).unwrap();
    }

    // ---- Attribute statics ----

    let attr_idents: HashMap<&str, String> = attributes
        .iter()
        .map(|a| (a.name.as_str(), ident_from(&a.name)))
        .collect();

    for attr in &attributes {
        let id = &attr_idents[attr.name.as_str()];

        write_static_str_slice(&mut out, &format!("ATTR_{id}_ELEMENTS"), &attr.elements);

        match &attr.values {
            ValuesJson::Enum { values } => {
                write_static_str_slice(&mut out, &format!("ATTR_{id}_VALUES"), values);
            }
            ValuesJson::Transform { functions } => {
                write_static_str_slice(&mut out, &format!("ATTR_{id}_FUNCTIONS"), functions);
            }
            ValuesJson::PreserveAspectRatio {
                alignments,
                meet_or_slice,
            } => {
                write_static_str_slice(&mut out, &format!("ATTR_{id}_ALIGNMENTS"), alignments);
                write_static_str_slice(
                    &mut out,
                    &format!("ATTR_{id}_MEET_OR_SLICE"),
                    meet_or_slice,
                );
            }
            _ => {}
        }

        writeln!(out).unwrap();
    }

    // ---- ELEMENTS array ----

    writeln!(out, "pub(crate) static ELEMENTS: &[ElementDef] = &[").unwrap();
    for el in &elements {
        let id = &el_idents[el.name.as_str()];
        let content_model = match &el.content_model {
            ContentModelJson::Simple(s) => match s.as_str() {
                "void" => "ContentModel::Void".to_string(),
                "text" => "ContentModel::Text".to_string(),
                other => panic!("unknown simple content_model: {other}"),
            },
            ContentModelJson::Children { .. } => {
                format!("ContentModel::Children(EL_{id}_CHILDREN)")
            }
        };
        writeln!(out, "    ElementDef {{").unwrap();
        writeln!(out, "        name: \"{}\",", escape(&el.name)).unwrap();
        writeln!(out, "        description: \"{}\",", escape(&el.description)).unwrap();
        writeln!(out, "        mdn_url: \"{}\",", escape(&el.mdn_url)).unwrap();
        writeln!(out, "        deprecated: {},", el.deprecated).unwrap();
        writeln!(out, "        baseline: None,").unwrap();
        writeln!(out, "        content_model: {content_model},").unwrap();
        writeln!(out, "        required_attrs: EL_{id}_REQUIRED_ATTRS,").unwrap();
        writeln!(out, "        attrs: EL_{id}_ATTRS,").unwrap();
        writeln!(out, "        global_attrs: {},", el.global_attrs).unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // ---- ATTRIBUTES array ----

    writeln!(out, "pub(crate) static ATTRIBUTES: &[AttributeDef] = &[").unwrap();
    for attr in &attributes {
        let id = &attr_idents[attr.name.as_str()];
        let values = match &attr.values {
            ValuesJson::Enum { .. } => format!("AttributeValues::Enum(ATTR_{id}_VALUES)"),
            ValuesJson::FreeText => "AttributeValues::FreeText".to_string(),
            ValuesJson::Color => "AttributeValues::Color".to_string(),
            ValuesJson::Length => "AttributeValues::Length".to_string(),
            ValuesJson::Url => "AttributeValues::Url".to_string(),
            ValuesJson::NumberOrPercentage => "AttributeValues::NumberOrPercentage".to_string(),
            ValuesJson::Transform { .. } => {
                format!("AttributeValues::Transform(ATTR_{id}_FUNCTIONS)")
            }
            ValuesJson::Viewbox => "AttributeValues::ViewBox".to_string(),
            ValuesJson::PreserveAspectRatio { .. } => {
                format!("AttributeValues::PreserveAspectRatio {{ alignments: ATTR_{id}_ALIGNMENTS, meet_or_slice: ATTR_{id}_MEET_OR_SLICE }}")
            }
            ValuesJson::Points => "AttributeValues::Points".to_string(),
            ValuesJson::PathData => "AttributeValues::PathData".to_string(),
        };
        writeln!(out, "    AttributeDef {{").unwrap();
        writeln!(out, "        name: \"{}\",", escape(&attr.name)).unwrap();
        writeln!(out, "        description: \"{}\",", escape(&attr.description)).unwrap();
        writeln!(out, "        mdn_url: \"{}\",", escape(&attr.mdn_url)).unwrap();
        writeln!(out, "        deprecated: {},", attr.deprecated).unwrap();
        writeln!(out, "        baseline: None,").unwrap();
        writeln!(out, "        values: {values},").unwrap();
        writeln!(out, "        elements: ATTR_{id}_ELEMENTS,").unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "];").unwrap();

    fs::write(&out_path, out).expect("failed to write catalog.rs");
}
