//! Build script that generates the baked SVG catalog from JSON fixtures,
//! browser-compat data, and spec-derived descriptions.
//!
//! The generated Rust source is written into `OUT_DIR` and then included by
//! the `svg-data` crate at compile time.

#[path = "build/bcd.rs"]
mod bcd;
#[path = "build/codegen.rs"]
mod codegen;
#[path = "build/spec.rs"]
mod spec;

use std::{collections::HashMap, error::Error, fmt::Write as _, fs, path::Path, time::SystemTime};

use bcd::BcdAttribute;
use codegen::{
    escape, format_baseline, format_browser_support, format_option_str, ident_from,
    write_static_str_slice,
};
use serde::Deserialize;

// ---- JSON schema types ----

#[derive(Deserialize)]
struct JsonElement {
    name: String,
    description: String,
    mdn_url: String,
    deprecated: bool,
    content_model: ContentModelJson,
    required_attrs: Vec<String>,
    attrs: Vec<String>,
    global_attrs: bool,
    #[serde(default)]
    category: Option<String>,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum ContentModelJson {
    Simple(String),
    Children { children: Vec<String> },
}

#[derive(Deserialize)]
struct JsonAttribute {
    name: String,
    description: String,
    mdn_url: String,
    deprecated: bool,
    values: ValuesJson,
    elements: Vec<String>,
}

#[derive(Deserialize)]
#[serde(tag = "type")]
#[serde(rename_all = "snake_case")]
enum ValuesJson {
    Enum {
        values: Vec<String>,
    },
    FreeText,
    Color,
    Length,
    Url,
    NumberOrPercentage,
    Transform {
        functions: Vec<String>,
    },
    Viewbox,
    PreserveAspectRatio {
        alignments: Vec<String>,
        meet_or_slice: Vec<String>,
    },
    Points,
    PathData,
}

// ---- Compat data types ----

#[derive(Clone, Default)]
struct BrowserSupportValue {
    chrome: Option<String>,
    edge: Option<String>,
    firefox: Option<String>,
    safari: Option<String>,
}

struct CompatEntry {
    deprecated: bool,
    experimental: bool,
    spec_url: Option<String>,
    baseline: Option<BaselineValue>,
    browser_support: Option<BrowserSupportValue>,
}

#[derive(Clone)]
enum BaselineValue {
    Widely { since: u16 },
    Newly { since: u16 },
    Limited,
}

impl BaselineValue {
    const fn rank(&self) -> u8 {
        match self {
            Self::Limited => 0,
            Self::Newly { .. } => 1,
            Self::Widely { .. } => 2,
        }
    }
}

// ---- Caching ----

const CACHE_MAX_AGE_SECS: u64 = 24 * 60 * 60;

fn ensure_cached(url: &str, dest: &Path, offline: bool) -> Result<bool, String> {
    if offline {
        if dest.exists() {
            println!(
                "cargo::warning=compat: using existing cache (offline mode): {}",
                dest.display()
            );
            return Ok(true);
        }
        println!(
            "cargo::warning=compat: no cache and offline mode — skipping {}",
            dest.display()
        );
        return Ok(false);
    }

    if dest.exists()
        && let Ok(meta) = fs::metadata(dest)
        && let Ok(modified) = meta.modified()
        && let Ok(age) = SystemTime::now().duration_since(modified)
        && age.as_secs() < CACHE_MAX_AGE_SECS
    {
        println!(
            "cargo::warning=compat: using cached {} (age {}s)",
            dest.display(),
            age.as_secs()
        );
        return Ok(true);
    }

    println!("cargo::warning=compat: downloading {url}");

    let mut response = ureq::get(url)
        .call()
        .map_err(|e| format!("fetch {url}: {e}"))?;

    let body = response
        .body_mut()
        .read_to_string()
        .map_err(|e| format!("read body {url}: {e}"))?;

    fs::write(dest, &body).map_err(|e| format!("write {}: {e}", dest.display()))?;

    Ok(true)
}

// ---- Code generation ----

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo::rerun-if-changed=data/elements.json");
    println!("cargo::rerun-if-changed=data/attributes.json");
    println!("cargo::rerun-if-env-changed=SVG_DATA_OFFLINE");

    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let out_dir = std::env::var("OUT_DIR")?;
    let out_dir = Path::new(&out_dir);
    let out_path = out_dir.join("catalog.rs");

    let elements_json = fs::read_to_string(manifest_dir.join("data/elements.json"))?;
    let attributes_json = fs::read_to_string(manifest_dir.join("data/attributes.json"))?;

    let elements: Vec<JsonElement> = serde_json::from_str(&elements_json)?;
    let attributes: Vec<JsonAttribute> = serde_json::from_str(&attributes_json)?;

    let offline = std::env::var("SVG_DATA_OFFLINE").is_ok();
    let compat = bcd::fetch_compat_data(out_dir);
    let spec_descriptions = spec::fetch_spec_descriptions(out_dir, offline);

    let mut out = String::with_capacity(16384);

    writeln!(out, "// @generated by build.rs -- do not edit")?;
    writeln!(out)?;

    // ---- Element statics ----

    let el_idents: HashMap<&str, String> = elements
        .iter()
        .map(|e| (e.name.as_str(), ident_from(&e.name)))
        .collect();

    for el in &elements {
        let id = &el_idents[el.name.as_str()];
        write_static_str_slice(
            &mut out,
            &format!("EL_{id}_REQUIRED_ATTRS"),
            &el.required_attrs,
        )?;
        write_static_str_slice(&mut out, &format!("EL_{id}_ATTRS"), &el.attrs)?;
        if let ContentModelJson::Children { children } = &el.content_model {
            write!(out, "static EL_{id}_CHILDREN: &[ElementCategory] = &[")?;
            for (i, cat) in children.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                write!(out, "ElementCategory::{cat}")?;
            }
            writeln!(out, "];")?;
        }
        writeln!(out)?;
    }

    // ---- Attribute statics ----

    let attr_idents: HashMap<&str, String> = attributes
        .iter()
        .map(|a| (a.name.as_str(), ident_from(&a.name)))
        .collect();

    for attr in &attributes {
        let id = &attr_idents[attr.name.as_str()];
        write_static_str_slice(&mut out, &format!("ATTR_{id}_ELEMENTS"), &attr.elements)?;
        match &attr.values {
            ValuesJson::Enum { values } => {
                write_static_str_slice(&mut out, &format!("ATTR_{id}_VALUES"), values)?;
            }
            ValuesJson::Transform { functions } => {
                write_static_str_slice(&mut out, &format!("ATTR_{id}_FUNCTIONS"), functions)?;
            }
            ValuesJson::PreserveAspectRatio {
                alignments,
                meet_or_slice,
            } => {
                write_static_str_slice(&mut out, &format!("ATTR_{id}_ALIGNMENTS"), alignments)?;
                write_static_str_slice(
                    &mut out,
                    &format!("ATTR_{id}_MEET_OR_SLICE"),
                    meet_or_slice,
                )?;
            }
            _ => {}
        }
        writeln!(out)?;
    }

    // ---- ELEMENTS array ----

    writeln!(out, "pub static ELEMENTS: &[ElementDef] = &[")?;
    for el in &elements {
        let id = &el_idents[el.name.as_str()];
        let content_model = match &el.content_model {
            ContentModelJson::Simple(s) => match s.as_str() {
                "foreign" => "ContentModel::Foreign".to_string(),
                "void" => "ContentModel::Void".to_string(),
                "text" => "ContentModel::Text".to_string(),
                other => panic!("unknown simple content_model: {other}"),
            },
            ContentModelJson::Children { .. } => {
                format!("ContentModel::Children(EL_{id}_CHILDREN)")
            }
        };

        let (deprecated, experimental, spec_url_str, baseline_str, browser_support_str) =
            compat.elements.get(&el.name).map_or_else(
                || {
                    (
                        el.deprecated,
                        false,
                        "None".to_string(),
                        "None".to_string(),
                        "None".to_string(),
                    )
                },
                |entry| {
                    (
                        entry.deprecated,
                        entry.experimental,
                        format_option_str(entry.spec_url.as_deref()),
                        format_baseline(entry.baseline.as_ref()),
                        format_browser_support(entry.browser_support.as_ref()),
                    )
                },
            );

        let name = escape(&el.name);
        let description = escape(spec_descriptions.get(&el.name).unwrap_or(&el.description));
        let mdn_url = escape(&el.mdn_url);
        let global_attrs = el.global_attrs;

        write!(
            out,
            r#"    ElementDef {{
        name: "{name}",
        description: "{description}",
        mdn_url: "{mdn_url}",
        deprecated: {deprecated},
        experimental: {experimental},
        spec_url: {spec_url_str},
        baseline: {baseline_str},
        browser_support: {browser_support_str},
        content_model: {content_model},
        required_attrs: EL_{id}_REQUIRED_ATTRS,
        attrs: EL_{id}_ATTRS,
        global_attrs: {global_attrs},
    }},
"#
        )?;
    }

    // BCD-only elements
    let curated_el_names: std::collections::HashSet<&str> =
        elements.iter().map(|e| e.name.as_str()).collect();
    let mut bcd_only_elements: Vec<(&str, &CompatEntry)> = compat
        .elements
        .iter()
        .filter(|(name, _)| !curated_el_names.contains(name.as_str()))
        .map(|(name, entry)| (name.as_str(), entry))
        .collect();
    bcd_only_elements.sort_by_key(|(name, _)| *name);

    for (name, entry) in &bcd_only_elements {
        let mdn_url = format!("https://developer.mozilla.org/docs/Web/SVG/Element/{name}");
        let fallback_desc = format!("The {name} SVG element.");
        let raw_name = *name;
        let name = escape(raw_name);
        let description = escape(spec_descriptions.get(raw_name).unwrap_or(&fallback_desc));
        let mdn_url = escape(&mdn_url);
        let deprecated = entry.deprecated;
        let experimental = entry.experimental;
        let spec_url_str = format_option_str(entry.spec_url.as_deref());
        let baseline_str = format_baseline(entry.baseline.as_ref());
        let browser_support_str = format_browser_support(entry.browser_support.as_ref());

        write!(
            out,
            r#"    ElementDef {{
        name: "{name}",
        description: "{description}",
        mdn_url: "{mdn_url}",
        deprecated: {deprecated},
        experimental: {experimental},
        spec_url: {spec_url_str},
        baseline: {baseline_str},
        browser_support: {browser_support_str},
        content_model: ContentModel::Void,
        required_attrs: &[],
        attrs: &[],
        global_attrs: true,
    }},
"#
        )?;
    }
    println!(
        "cargo::warning=compat: merged {} BCD-only elements into catalog",
        bcd_only_elements.len()
    );
    writeln!(out, "];")?;
    writeln!(out)?;

    // ---- BCD-only attribute statics ----

    let curated_names: std::collections::HashSet<&str> =
        attributes.iter().map(|a| a.name.as_str()).collect();
    let mut bcd_only: Vec<(&str, &BcdAttribute)> = compat
        .attributes
        .iter()
        .filter(|(name, _)| !curated_names.contains(name.as_str()))
        .map(|(name, bcd)| (name.as_str(), bcd))
        .collect();
    bcd_only.sort_by_key(|(name, _)| *name);

    for (name, bcd) in &bcd_only {
        let id = ident_from(name);
        write_static_str_slice(&mut out, &format!("ATTR_{id}_ELEMENTS"), &bcd.elements)?;
        writeln!(out)?;
    }
    println!(
        "cargo::warning=compat: merged {} BCD-only attributes into catalog",
        bcd_only.len()
    );

    // ---- ATTRIBUTES array ----

    writeln!(out, "pub static ATTRIBUTES: &[AttributeDef] = &[")?;

    for attr in &attributes {
        let id = &attr_idents[attr.name.as_str()];
        let values = match &attr.values {
            ValuesJson::Enum { .. } => format!("AttributeValues::Enum(ATTR_{id}_VALUES)"),
            ValuesJson::FreeText => "AttributeValues::FreeText".to_string(),
            ValuesJson::Color => "AttributeValues::Color".to_string(),
            ValuesJson::Length => "AttributeValues::Length".to_string(),
            ValuesJson::Url => "AttributeValues::Url".to_string(),
            ValuesJson::NumberOrPercentage => "AttributeValues::NumberOrPercentage".to_string(),
            ValuesJson::Transform { .. } => {
                format!("AttributeValues::Transform(ATTR_{id}_FUNCTIONS)")
            }
            ValuesJson::Viewbox => "AttributeValues::ViewBox".to_string(),
            ValuesJson::PreserveAspectRatio { .. } => format!(
                "AttributeValues::PreserveAspectRatio {{ alignments: ATTR_{id}_ALIGNMENTS, meet_or_slice: ATTR_{id}_MEET_OR_SLICE }}"
            ),
            ValuesJson::Points => "AttributeValues::Points".to_string(),
            ValuesJson::PathData => "AttributeValues::PathData".to_string(),
        };
        let (deprecated, experimental, spec_url_str, baseline_str, browser_support_str) =
            compat.attributes.get(&attr.name).map_or_else(
                || {
                    (
                        attr.deprecated,
                        false,
                        "None".to_string(),
                        "None".to_string(),
                        "None".to_string(),
                    )
                },
                |bcd| {
                    (
                        bcd.compat.deprecated,
                        bcd.compat.experimental,
                        format_option_str(bcd.compat.spec_url.as_deref()),
                        format_baseline(bcd.compat.baseline.as_ref()),
                        format_browser_support(bcd.compat.browser_support.as_ref()),
                    )
                },
            );
        let name = escape(&attr.name);
        let description = escape(&attr.description);
        let mdn_url = escape(&attr.mdn_url);

        write!(
            out,
            r#"    AttributeDef {{
        name: "{name}",
        description: "{description}",
        mdn_url: "{mdn_url}",
        deprecated: {deprecated},
        experimental: {experimental},
        spec_url: {spec_url_str},
        baseline: {baseline_str},
        browser_support: {browser_support_str},
        values: {values},
        elements: ATTR_{id}_ELEMENTS,
    }},
"#
        )?;
    }

    for (name, bcd) in &bcd_only {
        let id = ident_from(name);
        let mdn_url = format!("https://developer.mozilla.org/docs/Web/SVG/Attribute/{name}");
        let description = format!("The {name} SVG attribute.");
        let name = escape(name);
        let description = escape(&description);
        let mdn_url = escape(&mdn_url);
        let deprecated = bcd.compat.deprecated;
        let experimental = bcd.compat.experimental;
        let spec_url_str = format_option_str(bcd.compat.spec_url.as_deref());
        let baseline_str = format_baseline(bcd.compat.baseline.as_ref());
        let browser_support_str = format_browser_support(bcd.compat.browser_support.as_ref());

        write!(
            out,
            r#"    AttributeDef {{
        name: "{name}",
        description: "{description}",
        mdn_url: "{mdn_url}",
        deprecated: {deprecated},
        experimental: {experimental},
        spec_url: {spec_url_str},
        baseline: {baseline_str},
        browser_support: {browser_support_str},
        values: AttributeValues::FreeText,
        elements: ATTR_{id}_ELEMENTS,
    }},
"#
        )?;
    }

    writeln!(out, "];")?;
    writeln!(out)?;

    // ---- Category mapping ----

    let mut category_map: HashMap<&str, Vec<&str>> = HashMap::new();
    for el in &elements {
        if let Some(cat) = &el.category {
            category_map.entry(cat.as_str()).or_default().push(&el.name);
        }
    }

    writeln!(out, "#[allow(unreachable_patterns)]")?;
    writeln!(
        out,
        "pub const fn generated_elements_in_category(cat: ElementCategory) -> &'static [&'static str] {{"
    )?;
    writeln!(out, "    match cat {{")?;
    for names in category_map.values_mut() {
        names.sort_unstable();
    }
    let mut cats: Vec<&str> = category_map.keys().copied().collect();
    cats.sort_unstable();
    for cat in &cats {
        let Some(names) = category_map.get(cat) else {
            continue;
        };
        let names_str = names
            .iter()
            .map(|n| format!("\"{}\"", escape(n)))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "        ElementCategory::{cat} => &[{names_str}],")?;
    }
    writeln!(out, "        _ => &[],")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;

    fs::write(&out_path, out)?;
    Ok(())
}
