//! Build script that generates the baked SVG catalog from JSON fixtures,
//! browser-compat data, and spec-derived descriptions.
//!
//! The generated Rust source is written into `OUT_DIR` and then included by
//! the `svg-data` crate at compile time.

#[path = "build/bcd.rs"]
mod bcd;
#[path = "build/codegen.rs"]
mod codegen;
#[path = "build/spec.rs"]
mod spec;
#[path = "src/xlink.rs"]
pub(crate) mod xlink;

use std::{
    collections::{HashMap, HashSet},
    error::Error,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
    time::SystemTime,
};

use bcd::BcdAttribute;
use codegen::{
    escape, format_baseline, format_browser_support, format_option_str, ident_from,
    write_static_str_slice,
};
use serde::Deserialize;

// ---- JSON schema types ----

#[derive(Deserialize)]
struct JsonElement {
    name: String,
    description: String,
    mdn_url: String,
    deprecated: bool,
    content_model: ContentModelJson,
    required_attrs: Vec<String>,
    attrs: Vec<String>,
    global_attrs: bool,
    #[serde(default)]
    category: Option<String>,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum ContentModelJson {
    Simple(String),
    Children { children: Vec<String> },
}

#[derive(Deserialize)]
struct JsonAttribute {
    name: String,
    description: String,
    mdn_url: String,
    deprecated: bool,
    values: ValuesJson,
    elements: Vec<String>,
}

#[derive(Deserialize)]
#[serde(tag = "type")]
#[serde(rename_all = "snake_case")]
enum ValuesJson {
    Enum {
        values: Vec<String>,
    },
    FreeText,
    Color,
    Length,
    Url,
    NumberOrPercentage,
    Transform {
        functions: Vec<String>,
    },
    Viewbox,
    PreserveAspectRatio {
        alignments: Vec<String>,
        meet_or_slice: Vec<String>,
    },
    Points,
    PathData,
}

// ---- Compat data types ----

#[derive(Clone)]
enum BrowserVersionValue {
    Unknown,
    Version(String),
}

#[derive(Clone, Default)]
struct BrowserSupportValue {
    chrome: Option<BrowserVersionValue>,
    edge: Option<BrowserVersionValue>,
    firefox: Option<BrowserVersionValue>,
    safari: Option<BrowserVersionValue>,
}

struct CompatEntry {
    deprecated: bool,
    experimental: bool,
    spec_url: Option<String>,
    baseline: Option<BaselineValue>,
    browser_support: Option<BrowserSupportValue>,
}

#[derive(Clone)]
enum BaselineValue {
    Widely { since: u16 },
    Newly { since: u16 },
    Limited,
}

impl BaselineValue {
    const fn rank(&self) -> u8 {
        match self {
            Self::Limited => 0,
            Self::Newly { .. } => 1,
            Self::Widely { .. } => 2,
        }
    }

    const fn since(&self) -> Option<u16> {
        match self {
            Self::Widely { since } | Self::Newly { since } => Some(*since),
            Self::Limited => None,
        }
    }
}

// ---- Caching ----

const CACHE_MAX_AGE_SECS: u64 = 24 * 60 * 60;

fn ensure_cached(url: &str, dest: &Path, offline: bool) -> Result<bool, String> {
    if offline {
        if dest.exists() {
            println!(
                "cargo::warning=compat: using existing cache (offline mode): {}",
                dest.display()
            );
            return Ok(true);
        }
        println!(
            "cargo::warning=compat: no cache and offline mode — skipping {}",
            dest.display()
        );
        return Ok(false);
    }

    if dest.exists()
        && let Ok(meta) = fs::metadata(dest)
        && let Ok(modified) = meta.modified()
        && let Ok(age) = SystemTime::now().duration_since(modified)
        && age.as_secs() < CACHE_MAX_AGE_SECS
    {
        return Ok(true);
    }

    let mut response = ureq::get(url)
        .call()
        .map_err(|e| format!("fetch {url}: {e}"))?;

    let body = response
        .body_mut()
        .read_to_string()
        .map_err(|e| format!("read body {url}: {e}"))?;

    fs::write(dest, &body).map_err(|e| format!("write {}: {e}", dest.display()))?;

    Ok(true)
}

// ---- Code generation ----

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo::rerun-if-changed=data/elements.json");
    println!("cargo::rerun-if-changed=data/attributes.json");
    println!("cargo::rerun-if-env-changed=SVG_DATA_OFFLINE");

    let inputs = load_build_inputs()?;
    let mut out = String::with_capacity(16384);
    let element_idents = element_idents(&inputs.elements);
    let attribute_idents = attribute_idents(&inputs.attributes);

    writeln!(out, "// @generated by build.rs -- do not edit")?;
    writeln!(out)?;

    write_element_statics(&mut out, &inputs.elements, &element_idents)?;
    write_attribute_statics(&mut out, &inputs.attributes, &attribute_idents)?;
    write_elements_array(
        &mut out,
        &inputs.elements,
        &element_idents,
        &inputs.compat,
        &inputs.spec_descriptions,
    )?;
    write_bcd_only_attribute_statics(&mut out, &inputs.attributes, &inputs.compat)?;
    write_attributes_array(
        &mut out,
        &inputs.attributes,
        &attribute_idents,
        &inputs.compat,
    )?;
    write_category_mapping(&mut out, &inputs.elements)?;

    fs::write(&inputs.out_path, out)?;
    Ok(())
}

struct BuildInputs {
    out_path: PathBuf,
    elements: Vec<JsonElement>,
    attributes: Vec<JsonAttribute>,
    compat: bcd::CompatData,
    spec_descriptions: HashMap<String, String>,
}

fn load_build_inputs() -> Result<BuildInputs, Box<dyn Error>> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let out_dir = std::env::var("OUT_DIR")?;
    let out_dir = PathBuf::from(out_dir);
    let out_path = out_dir.join("catalog.rs");

    let elements_json = fs::read_to_string(manifest_dir.join("data/elements.json"))?;
    let attributes_json = fs::read_to_string(manifest_dir.join("data/attributes.json"))?;

    let elements: Vec<JsonElement> = serde_json::from_str(&elements_json)?;
    let attributes: Vec<JsonAttribute> = serde_json::from_str(&attributes_json)?;

    let offline = std::env::var("SVG_DATA_OFFLINE").is_ok();
    Ok(BuildInputs {
        out_path,
        elements,
        attributes,
        compat: bcd::fetch_compat_data(&out_dir),
        spec_descriptions: spec::fetch_spec_descriptions(&out_dir, offline),
    })
}

fn element_idents(elements: &[JsonElement]) -> HashMap<&str, String> {
    elements
        .iter()
        .map(|element| (element.name.as_str(), ident_from(&element.name)))
        .collect()
}

fn attribute_idents(attributes: &[JsonAttribute]) -> HashMap<&str, String> {
    attributes
        .iter()
        .map(|attribute| (attribute.name.as_str(), ident_from(&attribute.name)))
        .collect()
}

fn write_element_statics(
    out: &mut String,
    elements: &[JsonElement],
    element_idents: &HashMap<&str, String>,
) -> std::fmt::Result {
    for element in elements {
        let id = &element_idents[element.name.as_str()];
        write_static_str_slice(
            out,
            &format!("EL_{id}_REQUIRED_ATTRS"),
            &element.required_attrs,
        )?;
        write_static_str_slice(out, &format!("EL_{id}_ATTRS"), &element.attrs)?;
        if let ContentModelJson::Children { children } = &element.content_model {
            write!(out, "static EL_{id}_CHILDREN: &[ElementCategory] = &[")?;
            for (index, category) in children.iter().enumerate() {
                if index > 0 {
                    out.push_str(", ");
                }
                write!(out, "ElementCategory::{category}")?;
            }
            writeln!(out, "];")?;
        }
        writeln!(out)?;
    }

    Ok(())
}

fn write_attribute_statics(
    out: &mut String,
    attributes: &[JsonAttribute],
    attribute_idents: &HashMap<&str, String>,
) -> std::fmt::Result {
    for attribute in attributes {
        let id = &attribute_idents[attribute.name.as_str()];
        write_static_str_slice(out, &format!("ATTR_{id}_ELEMENTS"), &attribute.elements)?;
        match &attribute.values {
            ValuesJson::Enum { values } => {
                write_static_str_slice(out, &format!("ATTR_{id}_VALUES"), values)?;
            }
            ValuesJson::Transform { functions } => {
                write_static_str_slice(out, &format!("ATTR_{id}_FUNCTIONS"), functions)?;
            }
            ValuesJson::PreserveAspectRatio {
                alignments,
                meet_or_slice,
            } => {
                write_static_str_slice(out, &format!("ATTR_{id}_ALIGNMENTS"), alignments)?;
                write_static_str_slice(out, &format!("ATTR_{id}_MEET_OR_SLICE"), meet_or_slice)?;
            }
            _ => {}
        }
        writeln!(out)?;
    }

    Ok(())
}

fn write_elements_array(
    out: &mut String,
    elements: &[JsonElement],
    element_idents: &HashMap<&str, String>,
    compat: &bcd::CompatData,
    spec_descriptions: &HashMap<String, String>,
) -> std::fmt::Result {
    writeln!(out, "pub static ELEMENTS: &[ElementDef] = &[")?;

    for element in elements {
        write_curated_element(out, element, element_idents, compat, spec_descriptions)?;
    }

    let bcd_only_elements = bcd_only_elements(elements, compat);
    for &(name, entry) in &bcd_only_elements {
        write_bcd_only_element(out, name, entry, spec_descriptions)?;
    }

    writeln!(out, "];")?;
    writeln!(out)
}

fn write_curated_element(
    out: &mut String,
    element: &JsonElement,
    element_idents: &HashMap<&str, String>,
    compat: &bcd::CompatData,
    spec_descriptions: &HashMap<String, String>,
) -> std::fmt::Result {
    let id = &element_idents[element.name.as_str()];
    let content_model = match &element.content_model {
        ContentModelJson::Simple(simple_model) => match simple_model.as_str() {
            "foreign" => "ContentModel::Foreign".to_string(),
            "void" => "ContentModel::Void".to_string(),
            "text" => "ContentModel::Text".to_string(),
            other => panic!("unknown simple content_model: {other}"),
        },
        ContentModelJson::Children { .. } => format!("ContentModel::Children(EL_{id}_CHILDREN)"),
    };

    let spec_lifecycle = spec_lifecycle_expr(element.deprecated);
    let (deprecated, experimental, spec_url_str, baseline_str, browser_support_str) =
        compat.elements.get(&element.name).map_or_else(
            || {
                (
                    element.deprecated,
                    false,
                    "None".to_string(),
                    "None".to_string(),
                    "None".to_string(),
                )
            },
            |entry| {
                (
                    element.deprecated || entry.deprecated,
                    entry.experimental,
                    format_option_str(entry.spec_url.as_deref()),
                    format_baseline(entry.baseline.as_ref()),
                    format_browser_support(entry.browser_support.as_ref()),
                )
            },
        );

    let name = escape(&element.name);
    let description = escape(
        spec_descriptions
            .get(&element.name)
            .unwrap_or(&element.description),
    );
    let mdn_url = escape(&element.mdn_url);
    let global_attrs = element.global_attrs;

    write!(
        out,
        r#"    ElementDef {{
        name: "{name}",
        description: "{description}",
        mdn_url: "{mdn_url}",
        spec_lifecycle: {spec_lifecycle},
        deprecated: {deprecated},
        experimental: {experimental},
        spec_url: {spec_url_str},
        baseline: {baseline_str},
        browser_support: {browser_support_str},
        content_model: {content_model},
        required_attrs: EL_{id}_REQUIRED_ATTRS,
        attrs: EL_{id}_ATTRS,
        global_attrs: {global_attrs},
    }},
"#
    )
}

fn write_bcd_only_element(
    out: &mut String,
    name: &str,
    entry: &CompatEntry,
    spec_descriptions: &HashMap<String, String>,
) -> std::fmt::Result {
    let mdn_url = format!("https://developer.mozilla.org/docs/Web/SVG/Element/{name}");
    let fallback_description = format!("The {name} SVG element.");
    let raw_name = name;
    let name = escape(raw_name);
    let description = escape(
        spec_descriptions
            .get(raw_name)
            .unwrap_or(&fallback_description),
    );
    let mdn_url = escape(&mdn_url);
    let spec_lifecycle = "SpecLifecycle::Stable";
    let deprecated = entry.deprecated;
    let experimental = entry.experimental;
    let spec_url_str = format_option_str(entry.spec_url.as_deref());
    let baseline_str = format_baseline(entry.baseline.as_ref());
    let browser_support_str = format_browser_support(entry.browser_support.as_ref());

    write!(
        out,
        r#"    ElementDef {{
        name: "{name}",
        description: "{description}",
        mdn_url: "{mdn_url}",
        spec_lifecycle: {spec_lifecycle},
        deprecated: {deprecated},
        experimental: {experimental},
        spec_url: {spec_url_str},
        baseline: {baseline_str},
        browser_support: {browser_support_str},
        content_model: ContentModel::Void,
        required_attrs: &[],
        attrs: &[],
        global_attrs: true,
    }},
"#
    )
}

fn write_bcd_only_attribute_statics(
    out: &mut String,
    attributes: &[JsonAttribute],
    compat: &bcd::CompatData,
) -> std::fmt::Result {
    let bcd_only = bcd_only_attributes(attributes, compat);

    for (name, attribute) in &bcd_only {
        let id = ident_from(name);
        write_static_str_slice(out, &format!("ATTR_{id}_ELEMENTS"), &attribute.elements)?;
        writeln!(out)?;
    }

    Ok(())
}

fn write_attributes_array(
    out: &mut String,
    attributes: &[JsonAttribute],
    attribute_idents: &HashMap<&str, String>,
    compat: &bcd::CompatData,
) -> std::fmt::Result {
    writeln!(out, "pub static ATTRIBUTES: &[AttributeDef] = &[")?;

    for attribute in attributes {
        write_curated_attribute(out, attribute, attribute_idents, compat)?;
    }

    for (name, attribute) in bcd_only_attributes(attributes, compat) {
        write_bcd_only_attribute(out, name, attribute)?;
    }

    writeln!(out, "];")?;
    writeln!(out)
}

fn write_curated_attribute(
    out: &mut String,
    attribute: &JsonAttribute,
    attribute_idents: &HashMap<&str, String>,
    compat: &bcd::CompatData,
) -> std::fmt::Result {
    let id = &attribute_idents[attribute.name.as_str()];
    let values = attribute_values_expr(id, &attribute.values);
    let spec_lifecycle = spec_lifecycle_expr(attribute.deprecated);
    let (deprecated, experimental, spec_url_str, baseline_str, browser_support_str) =
        compat.attributes.get(&attribute.name).map_or_else(
            || {
                (
                    attribute.deprecated,
                    false,
                    "None".to_string(),
                    "None".to_string(),
                    "None".to_string(),
                )
            },
            |bcd_attribute| {
                (
                    attribute.deprecated || bcd_attribute.compat.deprecated,
                    bcd_attribute.compat.experimental,
                    format_option_str(bcd_attribute.compat.spec_url.as_deref()),
                    format_baseline(bcd_attribute.compat.baseline.as_ref()),
                    format_browser_support(bcd_attribute.compat.browser_support.as_ref()),
                )
            },
        );
    let name = escape(&attribute.name);
    let description = escape(&attribute.description);
    let mdn_url = escape(&attribute.mdn_url);

    write!(
        out,
        r#"    AttributeDef {{
        name: "{name}",
        description: "{description}",
        mdn_url: "{mdn_url}",
        spec_lifecycle: {spec_lifecycle},
        deprecated: {deprecated},
        experimental: {experimental},
        spec_url: {spec_url_str},
        baseline: {baseline_str},
        browser_support: {browser_support_str},
        values: {values},
        elements: ATTR_{id}_ELEMENTS,
    }},
"#
    )
}

fn write_bcd_only_attribute(
    out: &mut String,
    name: &str,
    attribute: &BcdAttribute,
) -> std::fmt::Result {
    let id = ident_from(name);
    let mdn_url = format!("https://developer.mozilla.org/docs/Web/SVG/Attribute/{name}");
    let description = format!("The {name} SVG attribute.");
    let name = escape(name);
    let description = escape(&description);
    let mdn_url = escape(&mdn_url);
    let spec_lifecycle = "SpecLifecycle::Stable";
    let deprecated = attribute.compat.deprecated;
    let experimental = attribute.compat.experimental;
    let spec_url_str = format_option_str(attribute.compat.spec_url.as_deref());
    let baseline_str = format_baseline(attribute.compat.baseline.as_ref());
    let browser_support_str = format_browser_support(attribute.compat.browser_support.as_ref());

    write!(
        out,
        r#"    AttributeDef {{
        name: "{name}",
        description: "{description}",
        mdn_url: "{mdn_url}",
        spec_lifecycle: {spec_lifecycle},
        deprecated: {deprecated},
        experimental: {experimental},
        spec_url: {spec_url_str},
        baseline: {baseline_str},
        browser_support: {browser_support_str},
        values: AttributeValues::FreeText,
        elements: ATTR_{id}_ELEMENTS,
    }},
"#
    )
}

fn write_category_mapping(out: &mut String, elements: &[JsonElement]) -> std::fmt::Result {
    const ALL_ELEMENT_CATEGORIES: &[&str] = &[
        "Container",
        "Shape",
        "Text",
        "Gradient",
        "Filter",
        "Descriptive",
        "Structural",
        "Animation",
        "PaintServer",
        "ClipMask",
        "LightSource",
        "FilterPrimitive",
        "TransferFunction",
        "MergeNode",
        "MotionPath",
        "NeverRendered",
    ];

    let mut category_map: HashMap<&str, Vec<&str>> = HashMap::new();
    for element in elements {
        if let Some(category) = &element.category {
            category_map
                .entry(category.as_str())
                .or_default()
                .push(&element.name);
        }
    }
    let mut unknown_categories: Vec<&str> = category_map
        .keys()
        .copied()
        .filter(|category| !ALL_ELEMENT_CATEGORIES.contains(category))
        .collect();
    unknown_categories.sort_unstable();
    assert!(
        unknown_categories.is_empty(),
        "unknown element categories in data/elements.json: {unknown_categories:?}"
    );

    writeln!(
        out,
        "pub const fn generated_elements_in_category(cat: ElementCategory) -> &'static [&'static str] {{"
    )?;
    writeln!(out, "    match cat {{")?;
    for names in category_map.values_mut() {
        names.sort_unstable();
    }
    for category in ALL_ELEMENT_CATEGORIES {
        if let Some(names) = category_map.get(category) {
            let names_str = names
                .iter()
                .map(|name| format!("\"{}\"", escape(name)))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                out,
                "        ElementCategory::{category} => &[{names_str}],"
            )?;
        } else {
            writeln!(out, "        ElementCategory::{category} => &[],")?;
        }
    }
    writeln!(out, "    }}")?;
    writeln!(out, "}}")
}

const fn spec_lifecycle_expr(is_deprecated: bool) -> &'static str {
    if is_deprecated {
        "SpecLifecycle::Deprecated"
    } else {
        "SpecLifecycle::Stable"
    }
}

fn attribute_values_expr(id: &str, values: &ValuesJson) -> String {
    match values {
        ValuesJson::Enum { .. } => format!("AttributeValues::Enum(ATTR_{id}_VALUES)"),
        ValuesJson::FreeText => "AttributeValues::FreeText".to_string(),
        ValuesJson::Color => "AttributeValues::Color".to_string(),
        ValuesJson::Length => "AttributeValues::Length".to_string(),
        ValuesJson::Url => "AttributeValues::Url".to_string(),
        ValuesJson::NumberOrPercentage => "AttributeValues::NumberOrPercentage".to_string(),
        ValuesJson::Transform { .. } => format!("AttributeValues::Transform(ATTR_{id}_FUNCTIONS)"),
        ValuesJson::Viewbox => "AttributeValues::ViewBox".to_string(),
        ValuesJson::PreserveAspectRatio { .. } => format!(
            "AttributeValues::PreserveAspectRatio {{ alignments: ATTR_{id}_ALIGNMENTS, meet_or_slice: ATTR_{id}_MEET_OR_SLICE }}"
        ),
        ValuesJson::Points => "AttributeValues::Points".to_string(),
        ValuesJson::PathData => "AttributeValues::PathData".to_string(),
    }
}

fn bcd_only_elements<'a>(
    elements: &[JsonElement],
    compat: &'a bcd::CompatData,
) -> Vec<(&'a str, &'a CompatEntry)> {
    let curated_element_names: HashSet<&str> = elements
        .iter()
        .map(|element| element.name.as_str())
        .collect();
    let mut bcd_only_elements: Vec<(&str, &CompatEntry)> = compat
        .elements
        .iter()
        .filter(|(name, _)| !curated_element_names.contains(name.as_str()))
        .map(|(name, entry)| (name.as_str(), entry))
        .collect();
    bcd_only_elements.sort_by_key(|(name, _)| *name);
    bcd_only_elements
}

fn bcd_only_attributes<'a>(
    attributes: &[JsonAttribute],
    compat: &'a bcd::CompatData,
) -> Vec<(&'a str, &'a BcdAttribute)> {
    let curated_attribute_names: HashSet<&str> = attributes
        .iter()
        .map(|attribute| attribute.name.as_str())
        .collect();
    let mut bcd_only_attributes: Vec<(&str, &BcdAttribute)> = compat
        .attributes
        .iter()
        .filter(|(name, _)| !curated_attribute_names.contains(name.as_str()))
        .map(|(name, bcd_attribute)| (name.as_str(), bcd_attribute))
        .collect();
    bcd_only_attributes.sort_by_key(|(name, _)| *name);
    bcd_only_attributes
}
